# Generated by Django 5.0.1 on 2024-03-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="video",
            new_name="file_path",
        ),
    ]
